URLbase: http://192.168.8.102:8000/
urls:
    user:
          userRegist: ['phone','qunid','password','name','identity','email','address','school','usertype','usericon','wechat','alipay','parameter1','parameter2','parameter3','parameter4','parameter5','parameter6','parameter7','parameter8','parameter9','parameter10','parameter11','parameter12','parameter13','parameter14','parameter15','parameter16','parameter17','parameter18','parameter19','parameter20']
          userLogin: ['phone','password','identity','school','qunid']
          updateuserstate: ['userid','qunid','userstate']
          updateUserPwd: ['id','oldpassword','newpassword']
          uploadUserIcon: ['id']
          updateuserinf: ['userid','phone','qunid','password','name','identity','email','address','id_number','push_userId','push_channelId','school','usertype','usericon','wechat','alipay','parameter1','parameter2','parameter3','parameter4','parameter5','parameter6','parameter7','parameter8','parameter9','parameter10','parameter11','parameter12','parameter13','parameter14','parameter15','parameter16','parameter17','parameter18','parameter19','parameter20']
          getUserInfo: ['userid']
          getalluser: ['page']
          getuserallimg: ['page','userid']
          getdifuser: ['page','userid','showtype']
          getallqunuser: ['page','userid']
    diary:
          adddiaryimg: ['content','qunid','qundiarytype','state','userid']
          adddiaryurl: ['qunid','qundiarytype','urltitle','state','userid','urlcontent','urlpath','img1']
          adddiaryvideo: ['qunid','qundiarytype','state','userid','content']
          adddiaryword: ['content','urltitle','urlpath','userid','qunid','state','img1','img2','img3','img4','img5','img6','img7','img8','img9','qundiarytype']
          deleteDiary: ['diaryid','userid']
          getdiaryurlcontent: ['diaryid']
          alluserdiarys: ['page','duserid','suserid']
          alluserqundiarys: ['page','duserid','suserid','qunid']
          alluserqundiarysfortype: ['page','duserid','suserid','qunid','typeindex']
          allmyqundiarys: ['page','userid']
          allmyqundiarys1: ['page','userid']
          queryallqundiary: ['page','userid']
          alldiarys: ['userid','qunid','qundiarytype','filtertype','field','keystr1','keystr2','page','pagesize']
          getalldiaryfortype: ['page','type']
          sousuodiary: ['userid','page','keystr']
          sousuoqundiaryforcontent: ['qunid','page','keystr']
          sousuoqundiaryfortitle: ['qunid','page','keystr']
          sousuouserdiary: ['userid','page','keystr']
          filterdiarys: ['userid','page','filter_text1','filter_text2','filter_text3']
          getdifdiary: ['showtype','page','userid']
          getguanzhudiary: ['page','userid']
          getdiarycommentforid: ['page','diaryid']
          getdiaryall: ['diaryid']
          updatediaryword: ['diaryid','content','urltitle','urlcontent','urlpath','userid','qunid','state','qundiarytype','img1','img2','img3','img4','img5','img6','img7','img8','img9']
          updatadiaryimg: ['diaryid','qunid','userid','state','diarycontent','qundiarytype']
          updatediarystate: ['diaryid','state']
          setdiaryid: ['diaryid']
    qun:
            addqun: ['userid','quntype','qunusetype','state','city','qu','Aname','Bname','AB','province','qunurl','gonggao','qunicon','type1','type2','type3','type4','type5','type6','type7','type8','type9','type10','type11','type12','type13','type14','type15']
            changequninf: ['userid','quntype','qunusetype','qunid','tuijiannum','shoucangnum','zannum','state','city','qu','Aname','Bname','AB','province','qunurl','gonggao','qunicon','type1','type2','type3','type4','type5','type6','type7','type8','type9','type10','type11','type12','type13','type14','type15']
            updatequnicon: ['id']
            getqunInfoBname: ['qun_Bname','qun_province','qun_city','qun_qu']
            getqunInfoAname: ['qun_Aname','qun_province','qun_city','qun_qu']
            getqunInfoAB: ['province','city','qu','bname','ab']
            getqunlInfoid: ['id']
            getqunInfoaddress: ['qun_province','qun_city','qun_qu']
            updataqun: ['userid','qun_Bname','qun_province','qun_city','qun_qu']
            joinqun: ['userid','qunid']
            delqunuser: ['userid','qunid']
            delqun: ['userid','qunid']
            getqunuser: ['userid','qunid','page']
            getqundiary: ['userid','qunid','page']
            getqundiaryfortype: ['userid','qunid','type','typeindex','page']
            getdiaryforuserqunuse: ['userid','qunusetype','page']
            getallqundiary: ['userid','qunid']
            getqunallimg: ['qunid','page']
            getquninfouserid: ['userid']
            getqunforuserqunuse: ['qunusetype','page','userid']
            getqunforqunuse: ['page','qunusetype']
            getdifqun: ['showtype','page','userid']
            getallqun: ['page','userid']
            filterqun: ['userid','page','filter_text1','filter_text2','filter_text3','filter_text4']
            getqunurl: ['qunid']
            sousuoqunforname: ['qunusetype','page','keystr']
            getmyschoolqun: ['identity','phone','password']
    chat:
          addchatmessage: ['content','receive_id','send_id','messagetype','contenttype','abid']
          addqunchatmessage: ['content','qunid','send_id','messagetype','contenttype']
          queryAllchatuser: ['receive_id']
          queryAllsixinwithhe: ['send_id','receive_id','page']
          queryAllsixin: ['receive_id','page']
          queryqunchat: ['page','receive_id','qunid']
          updatechatuserstate: ['send_id','receive_id','state']
          queryMessageForDate: ['message_date']
    comment:
          addComment: ['diaryid','userid','content']
          delcomment: ['userid','commentid']
          zan: ['commentid','zannum']
          queryCommentByDiaryId: ['diaryId']
    diarydeal:
          adddiaryword: ['diaryid','qunid','state','dealtype','userid','parameter1','parameter2','parameter3','parameter4','parameter5','parameter6','parameter7','parameter8','parameter9','parameter10']
          adddsomeiarydeal: ['liststr','qunid','state','dealtype','userid','parameter1','parameter2','parameter3','parameter4','parameter5','parameter6','parameter7','parameter8','parameter9','parameter10']
          deletedealdiary: ['dealdiaryid']
          getalldealdiaryforuserid: ['page','userid']
          getalldealdiaryforqunid: ['page','qunid']
          updatedealdiarystate: ['dealid','state']

    feedback:
          addFeedBack: ['name','contact','content']
    more:
          adddeal: ['deal','userid_source','diaryid_source','qunid_source','userid_destination','diaryid_destination','qunid_destination']
          changedeal: ['id','deal','userid_source','diaryid_source','qunid_source','userid_destination','diaryid_destination','qunid_destination']
          deldeal: ['id']
          deldealinfomore: ['deal','userid_source','diaryid_source','qunid_source','userid_destination','diaryid_destination','qunid_destination']
          getdealinfid: ['id']
          getdealinfhe: ['userid_source','diaryid_source','qunid_source','userid_destination','diaryid_destination','qunid_destination']
          getdealinfit: ['userid_source','diaryid_source','qunid_source','userid_destination','diaryid_destination','qunid_destination']
          getdealinfqun: ['userid_source','diaryid_source','qunid_source','userid_destination','diaryid_destination','qunid_destination']
          getmorelistinfmore: ['userid_source','diaryid_source','qunid_source','userid_destination','diaryid_destination','qunid_destination']
    mycaidan:
          addcaidan: ['content','qunid','qundiarytype','state','money','urltitle','urlcontent','userid']
          updatecaidanimg: ['content','qunid','qundiarytype','state','money','urltitle','urlcontent','userid','diaryid']
          updatecaidanword: ['content','qunid','qundiarytype','state','money','urltitle','urlcontent','userid','diaryid']
    tongzhi:
          addtongzhiimg: ['content','receive_id','state','messagetype','contenttype','send_id']
          addtongzhiurl: ['content','receive_id','state','messagetype','contenttype','send_id']
          addtongzhivideo: ['content','receive_id','state','messagetype','contenttype','send_id']
          addtongzhiword: ['content','receive_id','state','messagetype','contenttype','send_id']
          queryAlltongzhi: ['page']
          querytongzhifortype: ['page','messagetype']
    version:
          updateVersion: ['id','vcode']

log:
    file_name: test.log      # 输出日志文件名
    backup: 5                # 备份名
    console_level: WARNING  # 控制台输出等级
    file_level: DEBUG       # 文件输出等级
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'  # 打印输出格式